name: ubx CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: configure
      run: cmake -DENABLE_TEST=OFF .
    - name: make
      run: make -j8
